name: terraform plan

on:
  workflow_dispatch:
    inputs:
      dir: 
        type: string
        description: "working directory"
        required: true

      terraform_version: 
        description: 'Terraform Version'
        required: true
        default: 1.10.4

permissions:
  packages: write
  contents: write
  pull-requests: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_PR_TITLE: "[terraform/IAC] ${{ inputs.dir }}"

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    name: ${{ matrix.images.name }}
    steps:
      - name: Fail Workflow if secrets not defined
        shell: bash
        run: |
          if [ -z "${{ secrets.ENCRYPTION_PASSWORD }}" ]; then
            echo "Error: secret ENCRYPTION_PASSWORD is missing. This secret must be set, to encrypt the terraform plan prior to uploading to github artifacts" >&2
            exit 1
          fi

      - name: Checkout
        uses: actions/checkout@v4

      - uses: nxtcoder17/actions/pull-request-create@feat/tf-issues-and-pr
        id: pr
        with:
          github_token: ${{ env.GITHUB_TOKEN }}
          title: ${{ env.GITHUB_PR_TITLE }}
          body: "this PR once merged, audits, and tracks the terraform IAC changes"

      - name: creating output directory
        shell: bash
        id: output-dir
        run: |
          pushd "${{ inputs.dir }}"
          mkdir -p .actions-output
          plan_output_dir="$PWD/.actions-output"
          echo "TF_PLAN_OUTPUT_DIR=$plan_output_dir" | tee -a $GITHUB_ENV
          popd

          echo "${{inputs.dir}}" > $plan_output_dir/tf-working-dir

      - uses: nxtcoder17/actions/terraform-plan@feat/tf-issues-and-pr
        id: plan
        with:
          github_token: ${{ env.GITHUB_TOKEN }}
          working_directory: ${{ inputs.dir }}
          terraform_version: ${{ inputs.terraform_version  }}
          pr_number: ${{ steps.pr.outputs.PR_NUMBER }}
          plan_file: "${{ env.TF_PLAN_OUTPUT_DIR }}/tfplan"

      - name: encrypt terraform plan 
        shell: bash
        run: |
          echo "encrypting terraform plan file using AES-256-CBC algorithm"
          pushd "${{ env.TF_PLAN_OUTPUT_DIR }}"
          openssl enc -aes-256-cbc -pbkdf2 -iter 600000 -in tfplan -out "tfplan.enc" -pass pass:"${{ secrets.ENCRYTPTION_PASSWORD }}"
          mv tfplan.enc tfplan
          popd

      - name: Save Artifact
        id: save-plan
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.pr.outputs.PR_NUMBER }}-tf
          github_token: ${{ secrets.GITHUB_TOKEN }}
          path: |
            ${{ env.TF_PLAN_OUTPUT_DIR }}/tfplan
            ${{ env.TF_PLAN_OUTPUT_DIR }}/tf-working-dir

      - name: Terraform Plan Comment
        uses: nxtcoder17/actions/issue-comment@feat/tf-issues-and-pr
        with:
          github_token: ${{ inputs.GITHUB_TOKEN }}
          issue_number: ${{ steps.pr.outputs.PR_NUMBER }}
          body: |
            Terraform Plan:

            ```
            ${{ steps.plan.outputs.TF_PLAN_STDOUT }}
            ```

            Terraform Plan has been securely encrypted and uploaded to [Github Artifacts](steps.save-plan.outputs.artifact-url)
